- name: install service from template
  template:
    src: madek-mail.service
    dest: /etc/systemd/system/madek-mail.service
    owner: root
    group: root
    mode: 0644

- name: reload systemd
  systemd:
    daemon_reload: yes
  failed_when: false

- name: enabled and (re)start mail-service
  service:
    enabled: yes
    name: madek-mail
    state: restarted
